apiVersion: v1
kind: ConfigMap
metadata:
  name: policy
data:
  application.yml: |
    vendor:
      name: Spring Minikube 
    ---
    spring:
      profiles: development
    vendor:
      name: Spring Minikube Development
    ---
    spring:
      profiles: production
    vendor:
      name: Spring Minikube Production
