apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-deployment
  labels:
    app: policy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy
  template:
    metadata:
      labels:
        app: policy
    spec:
      containers:
      - name: policy
        image: policy:0.0.1
        ports:
        - containerPort: 800

---

apiVersion: v1
kind: Service
metadata:
  name: policy-service
spec:
  selector:
    app: policy
  type: ClusterIP  
  ports:
    - protocol: TCP
      port: 800
      targetPort: 800
      name: http